version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Build and packaging completed"
      - ls -lah target/

artifacts:
  files:
    - target/start-0.0.1-SNAPSHOT.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'