spring.application.name=start
server.address = localhost
server.port=8080
notification.type=email
debug=false

spring.datasource.url=jdbc:postgresql://santosh-postgres-prod.cgti6u4wg5m1.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres_prod
spring.datasource.password=Stormy_9987
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Enable H2 Web Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ==========================
# ACTUATOR CONFIGURATION
# ==========================

# Enable all actuator endpoints (DEV ONLY)
management.endpoints.web.exposure.include=*

# Show full health details
management.endpoint.health.show-details=always

# Base actuator path (default is /actuator)
management.endpoints.web.base-path=/actuator

#swagger/ open api configuration

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
spring.profiles.active=dev

# JWT configuration
jwt.secret=rD2x4f0z4Y8uF7ZPq4z8A0d4uYb9xQ9Xk6C1V0sY8
jwt.expiration=3600000

deploy.env=development